datasets:
  - ./data/datasets/complete/airfoil_self_noise.rds

mechanisms:
  - mcar

ratios:
  - 0.1
  - 0.2

reps: 3

methods:
  - mean
  - median

paths:
  amputed:   ./results/amputed/
  imputed:   ./results/imputed/
  scores:    ./results/scores/
  results:   ./results/

timeout_thresh: 36000
n_attempts: 2